env_id: "LunarLanderContinuous-v3"

trainer:
  accelerator: "auto"
  devices: 1
  max_steps: 100
  val_check_interval: 0
  log_every_n_steps: 0

agent:
  state_dim: 8
  action_dim: 2
  q_lr: 3e-4
  policy_lr: 3e-4
  log_alpha_lr: 3e-4
  gamma: 0.99
  tau: 0.005
  target_entropy: -2.0

buffer:
  max_size: 100

train:
  batch_size: 1
  # seed: 100
  start_steps: 10

wandb:
  project: "SAC-LunarLander"
